modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/GizmoTheMoonPig/luggage/issues"
license = "The MIT License (MIT)"

[[mods]]
modId = "luggage"
version = "${file.jarVersion}"
displayName = "Luggage"
itemIcon="luggage:luggage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/luggage"
logoFile = "luggage.png"
credits = "Original Luggage made by the Openblocks team"
authors = "GizmoTheMoonPig"
description = '''
Brings back the Luggage entity from OpenBlocks.
'''

[[dependencies.luggage]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0.102,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.luggage]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21]"
    ordering = "NONE"
    side = "BOTH"

[modproperties.luggage]
    configuredBackground="minecraft:textures/block/oak_planks.png"
